# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.2.5
maven_group = net.cerealcamera
archives_name = aviator-dreams-reloaded
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.20.1

# Dependencies
fabric_loader_version = 0.18.4
fabric_api_version = 0.92.7
forge_version = 47.4.16

immersive_aircraft_version = 1.4.0
mod_menu_version = 7.2.2