# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft properties
minecraft_version = 26.1.2

# Loader properties
fabric_loader_version = 0.19.5
neoforge_version = 26.1.2.112
enabled_platforms = fabric,neoforge

## Dependencies

# Mod dependency versions
fabric_api_version = 0.155.3
immersive_aircraft_version=1.5.2
mod_menu_version=18.0.2

### Key mod properties

## Details
archives_name=aviator_dreams_reloaded
maven_group=net.cerealcamera
id=aviator_dream
displayname=Aviator Dreams Reloaded
author=CerealCamera
website=https://modrinth.com/project/AOYDdieB
sources=https://github.com/CerealCamera/Aviator-Dreams-Reloaded
issues=https://github.com/CerealCamera/Aviator-Dreams-Reloaded/issues
mod_version=1.3.4
description=Realistic aircraft for Immersive Aircraft
license=GNU GPL 3.0
updater=https://api.modrinth.com/updates/AOYDdieB/forge_updates.json?neoforge_only
