modLoader = "javafml"
loaderVersion = "[@LOADER_MAJOR@,)"
issueTrackerURL = "https://github.com/CerealCamera/Aviator-Dreams-Reloaded"
license = "GPL-3.0-only"

[[mods]]
modId = "aviator_dream"
version = "${version}"
displayName = "Aviator Dreams Reloaded"
displayURL = "https://modrinth.com/mod/aviator-dreams-reloaded"
authors = "CerealCamera"
description = "Realistic aircraft for Immersive Aircraft"
logoFile = "icon.png"
itemIcon = "aviator_dream:douglas_dc1"

[[dependencies.aviator_dream]]
modId = "minecraft"
mandatory = true
versionRange = "[@MINECRAFT_VERSION@,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aviator_dream]]
modId = "forge"
mandatory = true
versionRange = "[@LOADER_MAJOR@,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aviator_dream]]
modId = "immersive_aircraft"
mandatory = true
versionRange = "[1.1.0,)"
ordering = "AFTER"
side = "BOTH"
