modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${issueTrackerUrl}"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${author}"
description = '''${description}'''
displayURL = "${websiteUrl}"
updateJSONURL = "${forgeUpdateUrl}"
logoFile = "icon.png"
itemIcon = "aviator_dream:douglas_dc1"

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoForgeVersion}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraftDependency}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "immersive_aircraft"
type = "required"
versionRange = "[1.2.2,)"
ordering = "AFTER"
side = "BOTH"